```makefile
# SPDX-FileCopyrightText: © 2024 Tiny Tapeout
# SPDX-License-Identifier: Apache-2.0

TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/src/tt_um_password_lock.v

TOPLEVEL = tt_um_password_lock

MODULE = test

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
```
